---
http://www.dalmacijanews.hr:
    prefix : dn
    upstream: "http://dkr7.aut-aut.rocks:6055"
    uris:
        /vijesti/ : 600
        /vijesti : 600
        /vijesti/hrvatska/ : 200
        /vijesti/svijet/ : 200
        /vijesti/biznis/ : 200
        /vijesti/znanost/ : 200
        /sport/ : 200
        /sport/split/ : 200
        /sport/hajduk/ : 200
        /sport/nogomet/ : 200
        /sport/ostalisportovi/ : 200
        /sport : 200
        /magazin/ : 200
        /magazin : 200
        /crnakronika/ : 200
        /crnakronika : 200
        /kolumne/ : 200
        "/css/style.min.css?v=0.6.4" : 6000
        /js/libs/emg.js : 6000

http://www.hzzo.hr:
    prefix : hz
    upstream : "http://dkr7.aut-aut.rocks:803"
    uris:
        /obavijest-osiguranicima-dopunskog-zdravstvenog-osiguranja: 600
        / : 600
        /dopunsko-zdravstveno-osiguranje : 600
        /dopunsko-zdravstveno-osiguranje/novosti : 600

mcservers:
    104.155.44.59 : 11211
expire_secs: 60
fetchtimeout : 7
datadogenabled : False
# Either "syslog" or a file path with filename to log, or "None" for no logging
logto : None
