---
http://www.aut-aut.hr:
    prefix: aa
    uris:
        / : 60000
        /style.min.css: 90000
        /index.min.js: 90000
        /content.details.js : 90000
        /res/jquery.mobile-1.1.0.min.js : 90000
        /jquery.magnific-popup.min.js : 90000
        /index.html : 7000
mcservers:
    memcache1 : 11211
    memcache2 : 11211
expire_secs: 60
fetchtimeout: 5

